#ifndef GETGLOBALCOORDINATE_GLOBAL_H
#define GETGLOBALCOORDINATE_GLOBAL_H

#include <QtCore/qglobal.h>

//#ifdef GETGLOBALCOORDINATE_LIB
//# define GETGLOBALCOORDINATE_EXPORT Q_DECL_EXPORT
//#else
//# define GETGLOBALCOORDINATE_EXPORT Q_DECL_IMPORT
//#endif

#endif // GETGLOBALCOORDINATE_GLOBAL_H
