# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

TEMPLATE = lib
TARGET = GetGlobalCoordinate
DESTDIR = ../../Win32/Release
QT += core widgets
CONFIG += release
DEFINES += QT_DLL QT_WIDGETS_LIB GETGLOBALCOORDINATE_LIB
INCLUDEPATH += ./GeneratedFiles \
    . \
    ./GeneratedFiles/Release
DEPENDPATH += .
MOC_DIR += ./GeneratedFiles/release
OBJECTS_DIR += release
UI_DIR += ./GeneratedFiles
RCC_DIR += ./GeneratedFiles
