#include "StdAfx.h"
#include <stdlib.h>
#include "VtkWriter.h"
#include "vec3fv.h"
#include "vec3iv.h"

#ifdef _WIN32
#include <fcntl.h>
#include <io.h>
#endif


CVtkWriter::CVtkWriter(void)
{
	// init of interface
	file = 0;
	vertex_buffer_alloc = 0;
	vertex_buffer = 0;
	triangle_buffer_alloc = 0;
	triangle_buffer = 0;

	m_nverts = -1;
	m_nfaces = -1;

	v_count = -1;
	f_count = -1;

	bb_min_f = 0;
	bb_max_f = 0;

	need_pre_order = false;
	offset_d = NULL;
}


CVtkWriter::~CVtkWriter(void)
{
	// clean-up  of interface
	if (vertex_buffer) free(vertex_buffer);
	if (triangle_buffer) free(triangle_buffer);

	if (v_count != -1)
	{
		close(); // user must have forgotten to close the mesh
	}

	if (bb_min_f) delete [] bb_min_f;
	if (bb_max_f) delete [] bb_max_f;
}

void CVtkWriter::set_nverts(int nverts)
{
	m_nfaces = nverts;
	vertex_buffer = (float*)realloc(vertex_buffer, sizeof(float)*3*nverts);
	vertex_buffer_alloc = nverts;
}

void CVtkWriter::set_nfaces(int nfaces)
{
	m_nfaces = nfaces;
	triangle_buffer = (int*)realloc(triangle_buffer, sizeof(int)*3*nfaces);
	triangle_buffer_alloc = nfaces;
}

bool CVtkWriter::open(FILE* file)
{
	if (file == 0)
	{
		return false;
	}

#ifdef _WIN32
	if (file == stdout)
	{
		if(_setmode( _fileno( stdout ), _O_TEXT ) == -1 )
		{
			fprintf(stderr, "ERROR: cannot set stdout to text (translated) mode\n");
		}
	}
#endif

	this->file = file;
	v_count = 0;
	f_count = 0;
	vertex_buffer_alloc = 1024;
	vertex_buffer = (float*)realloc(vertex_buffer, sizeof(float)*3*vertex_buffer_alloc);
	triangle_buffer_alloc = 2048;
	triangle_buffer = (int*)realloc(triangle_buffer, sizeof(int)*3*triangle_buffer_alloc);
	return (vertex_buffer != 0) && (triangle_buffer != 0);
}

void CVtkWriter::write_vertex(const float* v_pos_f)
{
	if (v_count == vertex_buffer_alloc)
	{
		vertex_buffer = (float*)realloc(vertex_buffer, sizeof(float)*3*vertex_buffer_alloc*2);
		vertex_buffer_alloc = vertex_buffer_alloc * 2;
	}
	VecCopy3fv(&(vertex_buffer[v_count*3]),v_pos_f);

	v_count++;
}

void CVtkWriter::write_triangle(const int* t_idx)
{
	if (f_count == triangle_buffer_alloc)
	{
		triangle_buffer = (int*)realloc(triangle_buffer, sizeof(int)*3*triangle_buffer_alloc*2);
		triangle_buffer_alloc = triangle_buffer_alloc * 2;
	}
	VecCopy3iv(&(triangle_buffer[f_count*3]),t_idx);

	f_count++;
}

void CVtkWriter::write_triangle(const int* t_idx, const bool* t_final)
{
	write_triangle(t_idx);
}

void CVtkWriter::write_finalized(int final_idx)
{
}

void CVtkWriter::close(bool close_file, bool update_header)
{
	int i;

	// write header
	fprintf(file, "# vtk DataFile Version 2.0\012");
	fprintf(file, "generated by LiDAR SCENE\012");
	fprintf(file, "ASCII\012");
	fprintf(file, "DATASET UNSTRUCTURED_GRID\012");

	// write vertices
	fprintf(file, "POINTS %d float\012",v_count);
	if (offset_d)
	{
		for(i = 0; i < v_count; i++)
		{
			fprintf(file, "%lg %lg %lg\012",offset_d[0]+vertex_buffer[3*i+0],offset_d[1]+vertex_buffer[3*i+1],offset_d[2]+vertex_buffer[3*i+2]);
		}
	}
	else
	{
		for(i = 0; i < v_count; i++)
		{
			fprintf(file, "%.8g %.8g %.8g\012",vertex_buffer[3*i+0],vertex_buffer[3*i+1],vertex_buffer[3*i+2]);
		}
	}

	// write triangles
	fprintf(file, "CELLS %d %d\012",f_count, f_count*5);
	for(i = 0; i < f_count; i++)
	{
		// it seems the mesquite loader only likes positive volume tets ... we have to invert the ones that our
		// code currently generates ... we'll have to change that back later.
		fprintf(file, "3 %d %d %d\012",triangle_buffer[3*i+0],triangle_buffer[3*i+1],triangle_buffer[3*i+2]);
	}

	// write cell types
	fprintf(file, "CELL_TYPES %d\012",f_count);
	for(i = 0; i < f_count; i++)
	{
		fprintf(file, "5\012");
	}

	if (close_file && file && file != stdout) fclose(file);
	file = 0;

	vertex_buffer_alloc = 0;
	if (vertex_buffer) free(vertex_buffer);
	vertex_buffer = 0;
	triangle_buffer_alloc = 0;
	if (triangle_buffer) free(triangle_buffer);
	triangle_buffer = 0;

	// close of interface
	if (m_nverts != -1 && m_nverts != v_count)  fprintf(stderr,"WARNING: set nverts %d but v_count %d\n",m_nverts,v_count);
	if (m_nfaces != -1 && m_nfaces != f_count)  fprintf(stderr,"WARNING: set nfaces %d but f_count %d\n",m_nfaces,f_count);
	m_nverts = v_count;
	m_nfaces = f_count;
	v_count = -1;
	f_count = -1;
}
